### ISSUE TITLE
can not find source file: hello.c

### ISSUE THREAD

**Issue by mumah-code** [dart-lang/samples#106]
In my program I found errors. It shows "can not find source file : hello.c"
![re1](https://user-images.githubusercontent.com/64001003/117955614-0c411900-b33a-11eb-9b28-453a61b0b61d.png)

![c](https://user-images.githubusercontent.com/64001003/117954774-2a5a4980-b339-11eb-85a8-18bcdf2aeabc.png)
![re](https://user-images.githubusercontent.com/64001003/117954807-33e3b180-b339-11eb-9885-c0249ea6833b.png)
![pr3](https://user-images.githubusercontent.com/64001003/117955520-f16ea480-b339-11eb-9075-0470a35c2b50.png)
![pr2](https://user-images.githubusercontent.com/64001003/117955530-f4699500-b339-11eb-95c5-18d05353bd21.png)
![pr1](https://user-images.githubusercontent.com/64001003/117955535-f5022b80-b339-11eb-8c96-75178ac653fa.png)

**Comment by jaygarcia** [comment]
@mumah-code , from my experience you need to [manually compile the libraries](https://github.com/dart-lang/samples/tree/master/ffi#readme) via `cmake`.  I'm not very familiar w/ CMake on Windows, but this process works fine  on Linux & Mac.

There is a related issue on how to make these libraries on Windows here:
https://github.com/dart-lang/samples/issues/57#issue-627898419

Hope this helps :)

**Comment by johnpryan** [comment]
Closing this as we are tracking windows support in https://github.com/dart-lang/samples/issues/57
