### ISSUE TITLE
Cannot run simple HTTP server example with `dart run`

### ISSUE THREAD

**Issue by mattwelke** [dart-lang/samples#120]
Completely new to Dart. I figured I'd start by checking the tutorials section of the website. It appears to be more example oriented than tutorial oriented. That's fine. I found this example because I'm very familiar with HTTP servers. This would make sense as a starting point for me given my experience with other programming languages. From reading the website, I know so far (and completing the steps in the https://dart.dev/tutorials/server/get-started#3-create-a-small-app tutorial) that one can run a Dart program with the `dart run` command. But when I run this sample, I get an error:

```
~/code/github.com/dart-lang/samples/server/simple (master) > dart run
  ╔════════════════════════════════════════════════════════════════════════════╗
  ║ The Dart tool uses Google Analytics to report feature usage statistics     ║
  ║ and to send basic crash reports. This data is used to help improve the     ║
  ║ Dart platform and tools over time.                                         ║
  ║                                                                            ║
  ║ To disable reporting of analytics, run:                                    ║
  ║                                                                            ║
  ║   dart --disable-analytics                                                 ║
  ║                                                                            ║
  ╚════════════════════════════════════════════════════════════════════════════╝

Resolving dependencies...
+ _fe_analyzer_shared 22.0.0
+ analyzer 1.7.2
+ args 2.1.1
+ async 2.7.0
+ boolean_selector 2.1.0
+ charcode 1.3.1
+ cli_util 0.3.2
+ collection 1.15.0
+ convert 3.0.1
+ coverage 1.0.3
+ crypto 3.0.1
+ file 6.1.2
+ frontend_server_client 2.1.0
+ glob 2.0.1
+ http 0.13.3
+ http_methods 1.1.0
+ http_multi_server 3.0.1
+ http_parser 4.0.0
+ io 1.0.2
+ js 0.6.3
+ lints 1.0.1
+ logging 1.0.1
+ matcher 0.12.10
+ meta 1.6.0 (2.0.0 available)
+ mime 1.0.0
+ node_preamble 2.0.1
+ package_config 2.0.0
+ path 1.8.0
+ pedantic 1.11.1
+ pool 1.5.0
+ pub_semver 2.0.0
+ shelf 1.1.4
+ shelf_packages_handler 3.0.0
+ shelf_router 1.0.0
+ shelf_static 1.0.0
+ shelf_web_socket 1.0.1
+ source_map_stack_trace 2.1.0
+ source_maps 0.10.10
+ source_span 1.8.1
+ stack_trace 1.10.0
+ stream_channel 2.1.0
+ string_scanner 1.1.0
+ term_glyph 1.2.0
+ test 1.17.9
+ test_api 0.4.1
+ test_core 0.3.29
+ test_process 2.0.1
+ typed_data 1.3.0
+ vm_service 7.1.0
+ watcher 1.0.0
+ web_socket_channel 2.1.0
+ webkit_inspection_protocol 1.0.0
+ yaml 3.1.0
Downloading shelf_static 1.0.0...
Downloading shelf_router 1.0.0...
Downloading path 1.8.0...
Downloading mime 1.0.0...
Downloading http_parser 4.0.0...
Downloading http_methods 1.1.0...
Downloading typed_data 1.3.0...
Downloading string_scanner 1.1.0...
Downloading collection 1.15.0...
Downloading test_process 2.0.1...
Downloading lints 1.0.1...
Downloading convert 3.0.1...
Downloading source_span 1.8.1...
Downloading term_glyph 1.2.0...
Downloading charcode 1.3.1...
Downloading http 0.13.3...
Downloading pedantic 1.11.1...
Downloading meta 1.6.0...
Downloading async 2.7.0...
Downloading shelf 1.1.4...
Downloading stream_channel 2.1.0...
Downloading stack_trace 1.10.0...
Downloading test 1.17.9...
Downloading webkit_inspection_protocol 1.0.0...
Downloading test_core 0.3.29...
Downloading test_api 0.4.1...
Downloading shelf_packages_handler 3.0.0...
Downloading pool 1.5.0...
Downloading package_config 2.0.0...
Downloading js 0.6.3...
Downloading boolean_selector 2.1.0...
Downloading source_maps 0.10.10...
Downloading source_map_stack_trace 2.1.0...
Downloading matcher 0.12.10...
Downloading frontend_server_client 2.1.0...
Downloading yaml 3.1.0...
Downloading web_socket_channel 2.1.0...
Downloading shelf_web_socket 1.0.1...
Downloading node_preamble 2.0.1...
Downloading io 1.0.2...
Downloading http_multi_server 3.0.1...
Downloading logging 1.0.1...
Downloading glob 2.0.1...
Downloading crypto 3.0.1...
Downloading coverage 1.0.3...
Downloading args 2.1.1...
Downloading vm_service 7.1.0...
Downloading file 6.1.2...
Downloading analyzer 1.7.2...
Downloading watcher 1.0.0...
Downloading pub_semver 2.0.0...
Downloading _fe_analyzer_shared 22.0.0...
Downloading cli_util 0.3.2...
Changed 53 dependencies!
Could not find `bin/container_server_example.dart` in package `container_server_example`.
```

If I look at the `pubspec.yaml`, which from reading the site I understood to be a manifest describing the program and its dependencies, I see at the top:

```yaml
name: container_server_example
```

So I think this needs to match the source code for it to run properly. I was able to get it to run by changing the file `bin/server.dart` file to `bin/container_server_example.dart`:

```
~/code/github.com/dart-lang/samples/server/simple (master) > dart run
Serving at http://0.0.0.0:8080
```

But I'm not sure what the example author's intentions were here. Should the file be called `server.dart` because the directory it's contained in describes the example with context, or should the file be called `container_server_example.dart` because the author wants to be specific or wants the example to stand on its own without the context provided by the rest of the repo? The word "container" here seems wrong because this example appears to be about an HTTP server, not an HTTP server and a way to dockerize one. The `Dockerfile` is a nice bonus, but it doesn't seem to be the core of what this example is about.

Since I think this behavior is not what someone running the examples as is is expected to encounter, I decided to report this as an issue.

**Comment by domesticmouse** [comment]
Assigning this to @kevmoo as I believe this is his sample.

In the mean time, I believe the easiest workaround is to run it as follows:

```console
$ dart run bin/server.dart
```

**Comment by mattwelke** [comment]
Yup, running `dart run bin/server.dart` seems to be the best option here. I read more on `dart run` in the docs, and it mentions that you can omit the file only if it happens to be located in the `bin` directory and matches the name of the package. So my understanding is that it's reasonable for devs to check the repo contents and figure out the right command to run it. For beginners, the fix may just be to include the command to run it in the readme.

**Comment by kevmoo** [comment]
Agree w/ @mattwelke – okay to close @domesticmouse ?

**Comment by domesticmouse** [comment]
@kevmoo are you going to update the README with running instructions, or should I?

**Comment by kevmoo** [comment]
By all means, @domesticmouse 😁
