### ISSUE TITLE
FFI synchronous callback samples

### ISSUE THREAD

**Issue by ykmnkmi** [dart-lang/samples#13]
And how to create function pointer?
```dart
typedef Pointer GlfwSetKeyCallback(Pointer<GLFWWindow> window, Pointer callback);
glfwSetKeyCallback(_window, dartFunction);```

**Comment by dcharkes** [comment]
With `Pointer.fromFunction`, see https://github.com/dart-lang/sdk/blob/master/tests/ffi/function_callbacks_test.dart.

**Comment by mrsac7** [comment]
Hi, I can work on this issue. I can wrtie `dart:ffi` bindings for a C program that uses callbacks.
> Maybe we should add an example using callbacks to this repo.

I've two examples [this](https://www.geeksforgeeks.org/callbacks-in-c/) and [insertion sort library](https://opensourceforu.com/2012/02/function-pointers-and-callbacks-in-c-an-odyssey/#highlighter_908025). Which one should I implement?

**Comment by dcharkes** [comment]
We've already got samples in the SDK for:

* [synchronous callbacks](https://github.com/dart-lang/sdk/blob/master/tests/ffi/function_callbacks_test.dart).
* [asynchronous callbacks](https://github.com/dart-lang/sdk/tree/master/samples/ffi/async) (through the native ports mechanism).

@mjohnsullivan @johnpryan are you open to PRs with this feature in this samples repo?

**Comment by johnpryan** [comment]
@dcharkes Yeah this would be a good use-case to cover in dart-lang/samples

**Comment by netgfx** [comment]
+1 for using callbacks and async/await for binding functions that are async on the C/or other lang program.

**Comment by jaygarcia** [comment]
Looks like this PR just surfaced w/ an Async function example: https://github.com/dart-lang/samples/pull/109 :)

**Comment by dcharkes** [comment]
> Looks like this PR just surfaced w/ an Async function example: #109 :)

Nice!

Note that this PR does synchronous callbacks, not asynchronous.
