### ISSUE TITLE
Can't build FFI samples on macOS

### ISSUE THREAD

**Issue by johnpryan** [dart-lang/samples#18]
see https://github.com/dart-lang/sdk/issues/39231 for details

**Comment by irvifa** [comment]
@domesticmouse probably this is not relevant anymore since it's fixed already isn't?

**Comment by domesticmouse** [comment]
I can confirm that the `ffi/hello_world` sample works on Dart 2.8.0-dev.18.0, but not on Dart 2.7.2. @johnpryan would you call this fixed now?

**Comment by johnpryan** [comment]
sgtm, thanks for verifying
