### ISSUE TITLE
ffi/hello_world test failing in `3.2.0-97.0.dev` and later

### ISSUE THREAD

**Issue by parlough** [dart-lang/samples#195]
The [hello_world sample](https://github.com/dart-lang/samples/tree/main/ffi/hello_world) is failing its [test](https://github.com/dart-lang/samples/blob/main/ffi/hello_world/test/hello_world_test.dart). It looks to be caused by https://github.com/dart-lang/sdk/commit/ef4984566b7534bb128325fe7f8b099208833e12.

I'm traveling so I don't currently have a chance to see if its an issue with that change, or if the code/test needs to be updated. I don't currently see why the test would be incorrect, but I may be missing something.

**Comment by parlough** [comment]
\cc @rmacnak-google @dcharkes Could one of you help determine if this is an issue with the change or if the sample's test needs to be updated? I'd appreciate the help.

**Comment by rmacnak-google** [comment]
This test is passing for me on Linux X64. What configuration are you running / what failure are you seeing?

**Comment by parlough** [comment]
Sorry I forgot to include a link to the workflow failure: https://github.com/dart-lang/samples/actions/runs/6048882725/job/16424667684?pr=194 which was running on ubuntu 22.04 x64. The output suggests stdout is empty.

I also reproduced the issue on macOS ARM64 and bisected to that commit. I however didn’t test on HEAD.

**Comment by rmacnak-google** [comment]
Weird, this test doesn't even call dart:io's exit.

**Comment by rmacnak-google** [comment]
Oh, I see. I changed more than I intended and now the embedder is calling `_exit` instead of `exit` for normal termination. Since the sample program calls only `printf` without `flush`, there's no output without the implicit `flush` that is part of `exit` but not `_exit`.

**Comment by parlough** [comment]
Thanks for looking into the failure @rmacnak-google! I tried out the fix and now everything is working as expected. 

---

Fixed by https://github.com/dart-lang/sdk/commit/53fb57ea5e97608c4f96cf5c3855eff24e720d19
