### ISSUE TITLE
FFI example project : NativeType problem

### ISSUE THREAD

**Issue by liupan163** [dart-lang/samples#31]
hello sir:
my problem is cann't where is the type of Utf8 ?
According to example project ,

structs.dart :
Pointer<Utf8>

ffi.dart:
class Pointer<T extends NativeType>

in native_type.dart:  there is seem to not a implement class that relative with the  Utf8 .

**Comment by dcharkes** [comment]
```dart
import "package:ffi/ffi.dart";
```

https://pub.dev/packages/ffi

**Comment by liupan163** [comment]
ok,thanks
