### ISSUE TITLE
WINDOWS/WIN32 API Problem allocating/reading UTF16

### ISSUE THREAD

**Issue by vieruuuu** [dart-lang/samples#37]
I have this code I can't get it to work, no errors are shown

```dart
import 'dart:ffi';

import 'package:ffi/ffi.dart';

class HWND extends Struct {}

typedef GetActiveWindowC = Pointer<HWND> Function();

typedef GetActiveWindowDart = Pointer<HWND> Function();

typedef GetWindowTextC = Int32 Function(Pointer<HWND> hWnd, Pointer<Utf8> lpString, Int32 nMaxCount);

typedef GetWindowTextDart = int Function(Pointer<HWND> hWnd, Pointer<Utf8> lpString, int nMaxCount);

void main() {
  var path = r'User32.dll';
  final dylib = DynamicLibrary.open(path);

  final GetActiveWindowPointer =
      dylib.lookup<NativeFunction<GetActiveWindowC>>('GetActiveWindow');
  final GetActiveWindowDart GetActiveWindow =
      GetActiveWindowPointer.asFunction<GetActiveWindowDart>();

  final GetWindowTextPointer =
      dylib.lookup<NativeFunction<GetWindowTextC>>('GetWindowTextA');
  final GetWindowTextDart GetWindowText =
      GetWindowTextPointer.asFunction<GetWindowTextDart>();

  final Pointer<HWND> hWnd = GetActiveWindow();

  final Pointer<Utf8> lpString = allocate();

  final int nMaxCount = 256;

  final result = GetWindowText(hWnd, lpString, nMaxCount);

  final text = Utf8.fromUtf8(lpString);

  print(result);
  print(text);
}
```

current output:
```
0

```

**Comment by vieruuuu** [comment]
ooops, im closing this, I used 'GetActiveWindow' instead of 'GetForegroundWindow', sorry for this

**Comment by domesticmouse** [comment]
It’s worth noting that Windows APIs are defined in terms of `wchar_t`, not UTF8.

**Comment by vieruuuu** [comment]
I tried using `wchat_t` but I couldn't figure out how to get it working using a utf8 pointer works sometimes.

Can you show me the proper way of doing it ?
Thanks for your time.

**Comment by vieruuuu** [comment]
> It’s worth noting that Windows APIs are defined in terms of `wchar_t`, not UTF8.

I tried using wchat_t but I couldn't figure out how to get it working using a utf8 pointer works sometimes.

Can you show me the proper way of doing it ?
Thanks for your time.

**Comment by domesticmouse** [comment]
Hey @mit-mit, do we have a story around converting dart strings to utf16? I looked in `dart:convert` but there isn't an encoding option. Help?

**Comment by domesticmouse** [comment]
Oh wait, Dart's native string is utf16 already, according to https://api.dart.dev/stable/2.7.1/dart-core/String-class.html

**Comment by domesticmouse** [comment]
And here is the utility class that you want to convert dart strings to Pointer<utf16> from the ffi package: https://pub.dev/documentation/ffi/latest/ffi/Utf16-class.html
