### ISSUE TITLE
Can't build the dynamic library. Facing error: "make: *** No targets specified and no makefile found" 

### ISSUE THREAD

**Issue by ramkumarravy** [dart-lang/samples#41]
I am trying to build the dynamic library for the "hello_world" example in the dart:ffi samples. While trying to do so, I am facing the following error:

> make: *** No targets specified and no makefile found.

I have installed the "make" from the following site: http://gnuwin32.sourceforge.net/packages/make.htm

Could you please advise me on this? Thanks in advance :).

OS: Windows

**Comment by domesticmouse** [comment]
Have you installed `cmake`? See the [ffi readme](https://github.com/dart-lang/samples/tree/master/ffi#building-native-libraries) for more information.

**Comment by ramkumarravy** [comment]
Yes, I did @domesticmouse. Have downloaded it from https://cmake.org/download/ and I'm using the cmake v3.17.0.

Also, when running the 'cmake .' command, it was instructed that following files will be generated. But the 'MakeFile' and 'CmakeScripts' are not generated. What would be the reason?

# CMake generated files and directories
CMakeCache.txt
CMakeFiles/
CmakeScripts/
Makefile
cmake_install.cmake

**Comment by domesticmouse** [comment]
On windows, I believe `cmake` will default to making a visual studio solution file. I don’t know cmake in depth, especially on windows. I’d suggest digging into cmake’s documentation, and asking questions on stackoverflow.com

**Comment by function1983** [comment]
Same as #57. It has step by step instruction to build dll file in Windows.
