### ISSUE TITLE
primitive FFI sample broken on macOS due to import problem

### ISSUE THREAD

**Issue by kakyoism** [dart-lang/samples#42]
## Problem

On macOS, running the primitive sample code after proper CMaking the C lib gives the following error

```sh
$ !dart
dart primitives.dart
Unhandled exception:
Invalid argument(s): Failed to load dynamic library (dlopen(./primitives_library/libprimtives.dylib, 1): image not found)
#0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:10:55)
#1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:19:12)
#2      main (file:///Users/kakyo/Desktop/_task/MMT/research/hello-mamguest/hello_dart/primitives/primitives.dart:41:32)
#3      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:19)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

## Fix

```sh
$ sdiff -l theirs/ffi/primitives/primitives.dart mine/primitives/primitives.dart | cat -n | grep -v -e '($'
5	import 'dart:ffi';					      |	import 'dart:ffi' as ffi;
41	  final dylib = DynamicLibrary.open(path);		      |	  final dylib = ffi.DynamicLibrary.open(path);
```

**Comment by domesticmouse** [comment]
Can you please submit the fix as a pull request?

**Comment by domesticmouse** [comment]
Also, I'm curious how your change fixes things. Is there two different `DynamicLibrary` objects in scope?

**Comment by dcantir** [comment]
@domesticmouse Hi, I got the same problem on my machine, but seems like the issue is using relative paths when trying to import the library (I get this message in the exception: "file system relative paths not allowed in hardened programs"). I will be glad to submit a PR!

**Comment by dcharkes** [comment]
> "file system relative paths not allowed in hardened programs"

On MacOS the dylib needs to be in the same or a sub folder of the dart executable. See https://github.com/dart-lang/sdk/issues/38314#issuecomment-585202804. (I'm not sure if you can fix the sample here, as the dart binary is part of the SDK folder and this simples repo is a different repo.)

**Comment by dcharkes** [comment]
> Also, I'm curious how your change fixes things. Is there two different `DynamicLibrary` objects in scope?

I did a breaking change, I changed those methods to be [extension methods](https://dart-review.googlesource.com/c/sdk/+/135463). Importing with `as` does not import the extension methods into the current scope.

**Comment by irvifa** [comment]
Hi I think the one proposed by @dcantir fix the problem and it's a minor one, can someone help take a look on that? Thanks!
