### ISSUE TITLE
extending LinkedListEntry Error for Custom LinkedList entry

### ISSUE THREAD

**Issue by Temurxon77** [dart-lang/samples#51]
```
class WidgetLinkedListEntry<T> extends LinkedListEntry {
  T widget;
  WidgetLinkedListEntry(this.widget);

  @override
  String toString() => '${super.toString()}: ${widget}';
}
```
I am getting error while extending from Linked List entry: 

> Error: Type argument 'LinkedListEntry<dynamic>' doesn't conform to the bound 'LinkedListEntry<E>' of the type variable 'E' on 'LinkedListEntry' in the supertype 'LinkedListEntry' of class 'WidgetLinkedListEntry' 'LinkedListEntry' is from 'dart:collection'. Try changing type arguments so that they conform to the bounds.  

Dart SDK: 2.7.0

**Comment by naveen246** [comment]
This should work:

class WidgetLinkedListEntry<T> extends LinkedListEntry<WidgetLinkedListEntry> {
  T widget;
  WidgetLinkedListEntry(this.widget);

  @override
  String toString() => '${super.toString()}: ${widget}';
}
