### ISSUE TITLE
DynamicLibrary.open() fails on windows for hello_world example

### ISSUE THREAD

**Issue by Lootwig** [dart-lang/samples#53]
I've confirmed the file exists and I can run the compiled hello_test.exe, yet when running `dart hello.dart` the program fails with output:

```
Unhandled exception:
Invalid argument(s): Failed to load dynamic library (193)
#0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:13:55)
#1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:22:12)
#2      main (file:///D:/Projects/hello_world/ffi/hello_world/hello.dart:18:36)
#3      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:19)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
```

As there is no detailed output as to why the command fails, I have no clue how to debug this. I might have just set up the GCC compiler wrong, although I guess that would cause a failing hello_test.exe as well.

`Dart VM version: 2.8.1 (stable) (Thu Apr 30 09:25:21 2020 +0200) on "windows_x64"`

**Comment by dcharkes** [comment]
It has to do with the path that it is expected to have the `.dll` file.

https://github.com/dart-lang/samples/blob/master/ffi/hello_world/hello.dart#L17

This expects the file to be on that path relative to the _executable_. When compiling to `hello_test.exe`, that executable is the executable. However, when using `dart.exe`, that is the executable (which is somewhere else on your machine).

Try changing the path to an absolute path to verify.

Unfortunately, I'm not aware of a good way to make the code both work for dart2native and dart.exe.

**Comment by Lootwig** [comment]
Using an absolute path yields the same error, unfortunately.

**Comment by dcharkes** [comment]
> although I guess that would cause a failing hello_test.exe as well.

That is why I would expect this to be a path issue. If you move the `hello_test.exe` to another folder, does it fail with the same error?

> Failed to load dynamic library (193)

https://www.google.com/search?q=193+dlopen+windows The error code seems to indicate some mixing and matching of 32 and 64 bit logic. (We do not support dart2native in 32 bit on Windows so that will always be 64 bit.) Did you install a 32 bit SDK instead of a 64 bit SDK?

**Comment by Lootwig** [comment]
I'm not sure TBH. I'm using MinGW and did look out to get the 64 bit version, however when running cmake, the option `-G "MinGW Makefiles"` only generates for mingw32-make, and that tool is also the only one included, there is no mingw64-make. So I really can't tell, is there a way to find out the target architecture of the created DLL?
