### ISSUE TITLE
Please add an example on how to pass an array of strings from dart to c

### ISSUE THREAD

**Issue by vikramkapoor** [dart-lang/samples#68]
E.g. How would emulate passing command line arguments  to a c function test_main(int argc, char* argv[]) from dart using FFI?

**Comment by dcharkes** [comment]
Hey @vikramkapoor,

`int` -> `Int32`
`char**` -> `Pointer<Pointer<Utf8>>` or `Pointer<Pointer<Int8>>`

**Comment by vikramkapoor** [comment]
Thank you very much!
