### ISSUE TITLE
platform dependent makefile

### ISSUE THREAD

**Issue by phanirithvij** [dart-lang/samples#7]
So for windows dynamiclib `gcc -dynamiclib -o hello.dll hello.o` will create a dll file but `dart hello.dart` fails because of lookup for the function `hello_world` fails.

```shell
$ dart hello.dart
Unhandled exception:
Invalid argument(s): Failed to lookup symbol (127)
#0      DynamicLibrary.lookup (dart:ffi-patch/ffi_dynamic_library_patch.dart:22:29)
#1      main (file:///D:/Projects/fun/dart-u-bastard/samples/ffi/hello_world/hello.dart:17:8)
#2      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:19)
#3      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```
So on windows `gcc -shared -o hello.dll hello.o` needs to be used.
Can the docs be updated? @mit-mit

**Comment by phanirithvij** [comment]
https://github.com/dart-lang/sdk/issues/38516 related

**Comment by kwalrath** [comment]
Did #8 fix this issue?

**Comment by phanirithvij** [comment]
Yes, `gcc -shared` needs to be used on windows. Closing it.
