### ISSUE TITLE
hello is there an example for dart string to c or vice versa

### ISSUE THREAD

**Issue by marcpar** [dart-lang/samples#70]
can you also give example recieving and sending string to C. and how do I trouble shoot 
\'.
Pointer<NativeType>: address=0x0

===== CRASH =====
si_signo=Segmentation fault(11), si_code=1, si_addr=0x4c0
version=2.9.1 (stable) (Unknown timestamp) on "linux_x64"
pid=499, thread=512, isolate_group=(nil)((nil)), isolate=(nil)((nil))
isolate_instructions=0, vm_instructions=5584e08a8f80
Stack dump aborted because InitialRegisterCheck failed.
Aborted

**Comment by domesticmouse** [comment]
Pointer of address 0x0 is a null pointer at a guess. Are you sure you are allocating the String?

**Comment by timsneath** [comment]
This includes examples of receiving / sending strings using FFI: https://github.com/dart-lang/samples/tree/master/ffi/structs
