### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by TigerWj** [dart-lang/samples#71]
Hello，there are no free() call to pointer return by malloc()，so，I want to ask who answer for the memory release ?

**Comment by TigerWj** [comment]
Is the GC in dart going to release the memory? Because memory leak seems happened in my project, even I have call free().

**Comment by TigerWj** [comment]
CPP
`char* QueryValidIp(const char* domain) {
    std::string ip;
    char * result;
    if (middleware::vipclient::helper::QueryValidIp(domain, &ip)) {
        result = (char *)malloc((ip.size() + 1) * sizeof(char));
        strcpy(result, ip.c_str());
    }
    else {
        result = (char *)malloc(sizeof(char));
        result[0] = '\0';
    }
    
    return result;
}`

Dart
` while (true) {
    String input = '';
    input = stdin.readLineSync();

    Pointer<Utf8> p1 = query_vaild_ip(Utf8.toUtf8(input));
    final ip = Utf8.fromUtf8(p1);
    print('$ip');
    free(p1);
   
    sleep(Duration(milliseconds: 200));
  }`

**Comment by dcharkes** [comment]
The Pointer returned by `Utf8.toUtf8(temp)` in `query_vaild_ip(Utf8.toUtf8(temp))` must be freed as well.

**Comment by TigerWj** [comment]
Yeah, thank you，I will try it out first. But, it seem didn't call free() in these samples

**Comment by TigerWj** [comment]
It  worked，thanks.
