### ISSUE TITLE
Samples for ffi in dart-lang/sdk repository are different

### ISSUE THREAD

**Issue by artemmiesianinov** [dart-lang/samples#73]
Hello, 

I looked into ffi samples in the https://github.com/dart-lang/sdk/tree/master/samples/ffi 
And I saw that there are different amount(versions) presented.
Do the examples from both sources still actual?

Thanks in advance.

**Comment by dcharkes** [comment]
Hi @artemmiesianinov 

The samples in the SDK repository work for the (non-released) version of the Dart SDK on the master branch. The samples in this repository work for the latest stable release.

Note that not all samples have been ported to here, but the majority of features should be available in stable.

**Comment by artemmiesianinov** [comment]
Thanks a lot for the explanation.
