### ISSUE TITLE
Cannot compile binary for iOS

### ISSUE THREAD

**Issue by w461** [dart-lang/samples#84]
Hi, I am trying to follow the primitives example. I have placed the Dart code into a simple Flutter app that shall be created together with Xcode for iOS. However, when using CMake to create the binary library, no appropriate output is generated.

CMakeLists.txt and all the other files are an unmodified copy in my project directory. I have added my hex identity in CMakeLists.txt.

I don't get the step with `cmake .` and `make`, since there is no make file present. I have also seen 2 open issues with regards to that, here. Instead, I used the following commands, taken from https://cmake.org/cmake/help/latest/manual/cmake-toolchains.7.html#cross-compiling-for-ios-tvos-or-watchos:

`$ cmake . -GXcode -DCMAKE_SYSTEM_NAME=iOS`

`$ cmake -S. -B_builds -GXcode     -DCMAKE_SYSTEM_NAME=iOS     "-DCMAKE_OSX_ARCHITECTURES=armv7;armv7s;arm64;i386;x86_64"     -DCMAKE_OSX_DEPLOYMENT_TARGET=9.3     -DCMAKE_INSTALL_PREFIX=../_install     -DCMAKE_XCODE_ATTRIBUTE_ONLY_ACTIVE_ARCH=NO     -DCMAKE_IOS_INSTALL_COMBINED=YES`

`$ cmake --build _builds --config Debug --target install`

This does not create a .dylib file, though no error is thrown. I am also still struggling with those cmake commands with another example, however, with that other example I have received a .dylib file using those commands.

Any ideas how to get this running are highly appreciated

**Comment by johnpryan** [comment]
You can now create an FFI plugin with `flutter create --template=plugin_ffi` on the latest Flutter beta channel. Let us know if you run into any issues with it!
